CREATE TABLE silver_CUST_AZ12 (
    CID VARCHAR(50),
    BDATE DATE,
    GEN VARCHAR(10),
    dwh_create_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE silver_LOC_A101 (
    CID VARCHAR(50),
    CNTRY VARCHAR(50),
     dwh_create_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE silver_PX_CAT_G1V2(
    ID VARCHAR(50),
    CAT VARCHAR(50),
    SUBCAT VARCHAR(50),
    MAINTENANCE VARCHAR(10),
     dwh_create_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
